apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threat-api
  namespace: threat-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  tls:
    - hosts:
        - api.threat.robertconsulting.net
      secretName: threat-api-tls
  rules:
    - host: api.threat.robertconsulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: threat-api
                port:
                  number: 80
